version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="prueba"
      - MYSQL_USER="admin"
      - MYSQL_PASSWORD="admin"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./proynodjs
    restart: unless-stopped
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true

volumes: 
  db:
