version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prueba
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./proynodjs
    restart: unless-stopped
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes: 
  db:
