version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="prueba"
    ports:
      - "3307:3307"
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./proynodjs
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - backend
    stdin_open: true
    tty: true

volumes: 
  db:

networks:
  backend:
